version: "3"

services:
  react-app:
    image: conangnr/find_em_client
    build: ./frontend/
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app

  api-server:
    image: conangnr/find_em_server
    build: ./api/
    ports:
      - "9000:9000"
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge